name: Pylint

# whenever there is new changes pushed on this repo, run the below jobs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout clones our repo and checks out the branch we're working in
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
